In [1]:
import pandas as pd

df = pd.read_csv("SOCR-HeightWeight.csv")

df.head()

   Index  Height(Inches)  Weight(Pounds)
0      1        65.78331        112.9925
1      2        71.51521        136.4873
2      3        69.39874        153.0269
3      4        68.21660        142.3354
4      5        67.78781        144.2971

In [3]:
x = df[["Height(Inches)"]]
y = df[["Weight(Pounds)"]]

In [4]:
df.isnull().any()

Index             False
Height(Inches)    False
Weight(Pounds)    False
dtype: bool

In [5]:
df.isnull().sum()

Index             0
Height(Inches)    0
Weight(Pounds)    0
dtype: int64

In [7]:
from sklearn.model_selection import train_test_split

In [8]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

In [13]:
x_train

       Height(Inches)
14246        69.38522
5615         67.02973
8726         67.93633
6908         68.76882
22179        67.75657
...               ...
13119        67.84388
17879        65.71394
7571         68.99119
14625        69.39405
22137        69.27105

[20000 rows x 1 columns]

In [14]:
from sklearn.linear_model import LinearRegression

In [15]:
model = LinearRegression()

In [16]:
model.fit(x_train, y_train)

LinearRegression()

In [19]:
y_pred = model.predict(x_test)

In [20]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [21]:
mean_absolute_error(y_test, y_pred)

8.131485145406803

In [22]:
mean_squared_error(y_test, y_pred)

103.63651083683861

In [23]:
r2_score(y_test, y_pred)

0.2577253344875563